[package]
name = "mystsh"
version = "0.0.1"
edition = "2024"
description = "Mystical shell parser, formatter, and interpreter with Bash support"
license = "MIT"

[dependencies]
os_pipe = "1.2.1"
libc = "0.2.172"