name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu

    env:
      RUSTFLAGS: "-C target-cpu=native"
      RUST_BACKTRACE: full
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: rustup toolchain install stable --profile minimal --target ${{ matrix.target }}
      - run: rustup component add rustfmt clippy
      - run: cargo fetch
      - run: make lint
      - name: cargo test build
        run: cargo build --tests --release
      - name: cargo test
        run: cargo test --release