name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}

    env:
      RUSTFLAGS: "-C target-cpu=native"
      RUST_BACKTRACE: full
      CARGO_TERM_COLOR: always
      CARGO_BUILD_TARGET: ${{ matrix.target }}

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}
      - run: rustup toolchain install stable --profile minimal --target ${{ matrix.target }}
      - run: rustup component add rustfmt clippy
      - run: cargo fetch --target ${{ matrix.target }}
      - run: make lint
      - name: cargo test build
        run: cargo build --tests --release --target ${{ matrix.target }}
      - name: cargo test
        run: cargo test --release --target ${{ matrix.target }}
      - name: make test-if
        run: make test-if